all:
  children:
    servers:
      hosts:
        calypso:
          ansible_host: 192.168.10.10
          ansible_user: clay
          deploy_path: /home/clay
        atlantis:
          ansible_host: 192.168.10.6
          ansible_user: clay
          deploy_path: /home/clay
        cerritos:
          ansible_host: 192.168.10.52
          ansible_user: clay
          deploy_path: /home/clay
